import datetime

BEG_DATE = datetime.date(2014,1,1)
TDEE_OFFSET = 460
BF_OFFSET = 208

DEFAULT_LIFT = 'Squat'
CULL_PERCENTAGE = 10

INPUT_PATH_DIET = ''
INPUT_PATH_GOAL = ''
INPUT_PATH_MOOD = ''
INPUT_PATH_RECORDS = ''
INPUT_PATH_LIFTS = ''
INPUT_FILENAME = 'page.html'
DRIVE_PATH = ''

VERBOSE = True